### ISSUE TITLE
compressionLevel is destroying the backend and frontend

### ISSUE THREAD

**Issue by QuingKhaos** [platformsh/platformsh-example-typo3#22]
Activating gzip compression destroys the backend and the frontend (if compressJs/Css = 1), because of the generation of .gzip files, but yet missing Content-Encoding headers.

```php
    $GLOBALS['TYPO3_CONF_VARS']['BE']['compressionLevel'] = 9;
    $GLOBALS['TYPO3_CONF_VARS']['FE']['compressionLevel'] = 9;
```

I wish TYPO3 would use the official `.gz` extension and not `.gzip`, so nginx would automatically pick that up. Of course TYPO3 would need to not request the .gzip/.gz files, instead it should request the default files, because the server can decide, which file to deliver...

**Comment by W4ldgeist** [comment]
Is there a solution for this problem? .gz is the standard across the web and .gzip is causing problems with nginx.
