### ISSUE TITLE
MySql  character set should be utf8

### ISSUE THREAD

**Issue by mvoehringer** [platformsh/platformsh-example-typo3#4]
Here is the messages form the TYPO3 Reporst module.

> MySQL Database Character Set  
> 
> Wrong value detected
> Your default database uses character set "latin1", but only "utf8" or "utf8mb4" is supported with TYPO3.

I'm very new to platform.sh and can't find the documentation how to configure these

**Comment by dkd-dobberkau** [comment]
This is a cosmetic issue of TYPO3 at the present state. See #1 for this.

**Comment by mvoehringer** [comment]
ok, the Upgrade Wizard wizard fixed this for me.
