### ISSUE TITLE
composer.lock file should be .gitignored

### ISSUE THREAD

**Issue by twaurisch** [platformsh/platformsh-example-typo3#7]
Made my first steps with deploying TYPO3 to platform.sh today. With this example script it's nearly a no-brainer to roll out a TYPO3 instance.

But one thing I'm confused about. If you update the _composer.json_ and push the changes to platform.sh the environment will not be updated. It's because the composer.lock is still the same.
In my opinion it makes more sense not pushing the lock-file to platform.sh, to make the changes available without an local _composer update_.

**Comment by ksjogo** [comment]
Adding the composer lock ensures that we can test the same version you will be installing. E.g. typo3_console had an (for us) breaking update crashing our build, the composer.lock protects against that, so I would prefer to keep it.
If somebody wants to change the local behaviour he could remove the lock from his repository (and verify when deploying (which we can't do for all upstream updates)).

**Comment by ksjogo** [comment]
Additionally though we should recommend/document the flag --ignore-platform-reqs of composer update, if somebody has an old PHP version or other incompatiblities on his local system which won't break on the platform instance.

**Comment by bauschan** [comment]
IMHO it is mandatory to have a composer.lock in the repo. This ensures the same dependencies are used in production as in development. It also means composer doesn’t need to do dependency resolution and version lookups, improving deployment performance.
If you adjust the composer.json file it is up to you to update the composer.lock accordingly.
