### ISSUE TITLE
Warnings in the reports module

### ISSUE THREAD

**Issue by dkd-dobberkau** [platformsh/platformsh-example-typo3#9]
There are warnings in the reports module. I am not sure if we need to disable those warnings if we know we are running on platform.sh 

File System 	Directory not writable
/app/web/typo3temp/ must be writable.
/app/web/typo3conf/ must be writable.
/app/web/typo3conf/ext/ should be writable.
typo3conf/l10n/ does not exist. Also note that it should be writable, if it did exist.

How do we deal with the l10n directory note too?

**Comment by JGrubb** [comment]
Hi, see the notes in this issue - https://github.com/platformsh/platformsh-example-typo3/issues/11

**Comment by JGrubb** [comment]
You'll need to adjust your `mounts` settings in the `.platform.app.yaml` accordingly.  Thank you.

**Comment by ksjogo** [comment]
lion will be added to the mounts but the others need not/should not be writeable with version 8 so these checks should be adapted.
